# The restaurant package is Chapter 7 from "The Rust Programming Language"

[package]
name = "restaurant"
version = "0.1.0"
authors = []
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
